spring:
  application:
    name: user-config-server
server:
  port: 1000
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8762/eureka/
      instance:
      hostname: localhost
    
      
      